openapi: 3.0.0
info:
  title: E-Commerce API
  contact: {}
  version: '1.0'
servers:
- url: https://e-commerce-api-tk1s.onrender.com/api/v1
  variables: {}
paths:
  /auth/register:
    post:
      tags:
      - Auth
      summary: Register User
      operationId: RegisterUser
      parameters: []
      requestBody:
        description: '"name", "email" and "password" all are necessary.<br>No neeed to verify email. "email" syntax must be correct.<br>"email" must be unique'
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/RegisterUserRequest'
              - example:
                  name: Bob
                  email: bob@gmail.com
                  password: secret
            example:
              name: Bob
              email: bob@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/login:
    post:
      tags:
      - Auth
      summary: Login User
      operationId: LoginUser
      parameters: []
      requestBody:
        description: '"email" and "password" both are required.'
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/LoginUserRequest'
              - example:
                  email: bob@gmail.com
                  password: secret
            example:
              email: bob@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/logout:
    get:
      tags:
      - Auth
      summary: Logout User
      operationId: LogoutUser
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/delete-account:
    delete:
      tags:
      - Auth
      summary: Delete User
      operationId: DeleteUser
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /product:
    get:
      tags:
      - Products
      summary: Get All Products
      operationId: GetAllProducts
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
    post:
      tags:
      - Products
      summary: Create Product
      operationId: CreateProduct
      parameters: []
      requestBody:
        description: '"name", "price", "boughtYear" and "brand" are necessary to provide.<br>"description" is optional.<br>You must be logged in to create product'
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateProductRequest'
              - example:
                  name: albany sectional
                  price: 110
                  boughtYear: 2005
                  brand: liddy
                  description: Hello, Wolrd!
            example:
              name: albany sectional
              price: 110
              boughtYear: 2005
              brand: liddy
              description: Hello, Wolrd!
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /product/search:
    get:
      tags:
      - Products
      summary: Search Products
      operationId: SearchProducts
      parameters:
      - name: name
        in: query
        description: 'Specify product name or a part of it.'
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: 
      - name: brand
        in: query
        description: 'Specify brand name or a part of it.'
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: 
      - name: owner
        in: query
        description: 'Specify owner id'
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: 649ed494153da89561db4f39
      - name: description
        in: query
        description: 'Specify keywords to search in description.'
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: 
      - name: price
        in: query
        description: 'specify one of the following operators: <, <=, >, >=.<br>After each operator specify the value.<br>To specify different intervals use comma as shown below'
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: '>=5,<=309'
      - name: boughtYear
        in: query
        description: 'Same syntax as price field.'
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: '>=1990,<=2005'
      - name: sort
        in: query
        description: 'Specify fields in space separated format.<br>Put a negative sign before a field to sort in descending order.'
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: -name price
      - name: select
        in: query
        description: 'Specify fields in space separated format.<br>If you want to exclude instead of include field, put - sign before all fields.<br>This is a projection field which works just like mongodb'
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: -boughtYear -brand -createdAt -updatedAt
      - name: page
        in: query
        description: 'Specify the page number you want to see.'
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: 1
      - name: limit
        in: query
        description: 'Specify how many products you want in one page.'
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: 5
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /product/my-products:
    get:
      tags:
      - Products
      summary: Get User Created Products
      operationId: GetUserCreatedProducts
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  
  /product/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: Specify product id
    get:
      tags:
      - Products
      summary: Get Single Product
      operationId: GetSingleProduct
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
    delete:
      tags:
      - Products
      summary: Delete Product
      operationId: DeleteProduct
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    patch:
      tags:
      - Products
      summary: Update Product
      operationId: UpdateProduct
      parameters: []
      requestBody:
        description: 'Only "name", "brand", "price", "boughtYear" and "description" can be updated.<br>A product can be updated or deleted only by its owner'
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateProductRequest'
              - example:
                  boughtYear: 2018
            example:
              boughtYear: 2018
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /cart:
    get:
      tags:
      - Cart
      summary: Get User Cart
      operationId: GetUserCart
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /cart/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: Specify product id
    post:
      tags:
      - Cart
      summary: Add Product To Cart
      operationId: AddProductToCart
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    delete:
      tags:
      - Cart
      summary: Delete Product From Cart
      operationId: DeleteProductFromCart
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
components:
  schemas:
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
      - name
      - email
      - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: Aditya
        email: aditya@gmail.com
        password: password
    LoginUserRequest:
      title: LoginUserRequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: aditya@gmail.com
        password: password
    CreateProductRequest:
      title: CreateProductRequest
      required:
      - name
      - price
      - boughtYear
      - brand
      - description
      type: object
      properties:
        name:
          type: string
        price:
          type: integer
          format: int32
        boughtYear:
          type: integer
          format: int32
        brand:
          type: string
        description:
          type: string
      example:
        name: albany sectional
        price: 110
        boughtYear: 2005
        brand: liddy
        description: Hello, Wolrd!
    UpdateProductRequest:
      title: UpdateProductRequest
      required:
      - boughtYear
      type: object
      properties:
        boughtYear:
          type: integer
          format: int32
      example:
        boughtYear: 2018
tags:
- name: Auth
- name: Products
- name: Cart